App\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      column: name
    price:
      type: integer
      column: price
